# Generated by Django 3.2.18 on 2023-07-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitingcompany',
            name='corporate_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
