# Generated by Django 3.2.18 on 2023-07-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recruitingcompany_corporate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='holiday',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='working_hours',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
