# Generated by Django 3.2.18 on 2023-07-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='shift_pattern',
        ),
    ]
