# Generated by Django 3.2.18 on 2023-07-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_job_shift_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
