# Generated by Django 3.2.18 on 2023-07-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230719_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
