# Generated by Django 3.2.18 on 2023-08-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_jobcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='smoking_prevention_measure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='trial_period',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
