# Generated by Django 3.2.18 on 2023-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230803_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='trigger',
            field=models.CharField(blank=True, default='detail_click', max_length=50),
        ),
    ]
