# Generated by Django 3.2.18 on 2023-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_record_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='trigger',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
