# Generated by Django 3.2.18 on 2023-08-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_record_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
