# Generated by Django 3.2.18 on 2023-08-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230807_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitingcompany',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
