# Generated by Django 3.2.18 on 2023-08-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20230813_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_appeal_layer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_appeal_remote',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
