# Generated by Django 3.2.18 on 2023-08-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20230813_1523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationRecruitingCompany',
            new_name='OrganizationCompany',
        ),
    ]
