# Generated by Django 3.2.18 on 2023-08-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_recruitingcompanytag_organizationcompanytag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationcompanytag',
            old_name='organization_recruiting_company_id',
            new_name='organization_company_id',
        ),
    ]
