# Generated by Django 3.2.18 on 2023-08-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_organization_recruiting_company_id_organizationcompanytag_organization_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
