# Generated by Django 3.2.18 on 2023-08-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_job_is_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationcompany',
            name='tag_id',
        ),
        migrations.DeleteModel(
            name='OrganizationCompanyTag',
        ),
    ]
