# Generated by Django 3.2.18 on 2023-08-25 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_job_organization_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='recruiting_company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.recruitingcompany'),
        ),
    ]
