# Generated by Django 3.2.18 on 2023-08-27 15:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_job_recruiting_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerHistoryNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_send', models.BooleanField(blank=True, db_index=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.record')),
            ],
        ),
    ]
