# Generated by Django 3.2.18 on 2023-08-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_jobseekerhistorynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcompany',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
