# Generated by Django 3.2.18 on 2023-08-29 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_organizationcompany_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcompany',
            name='recruiting_company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.recruitingcompany'),
        ),
    ]
