# Generated by Django 3.2.18 on 2023-09-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_organizationcompany_recruiting_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
