# Generated by Django 3.2.18 on 2023-09-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_jobseeker_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="is_checked",
            field=models.BooleanField(default=True),
        ),
    ]
