# Generated by Django 3.2.18 on 2023-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_proposal_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_salary_yen',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary_yen',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
