# Generated by Django 3.2.18 on 2023-09-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20230904_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='min_salary',
        ),
    ]
