# Generated by Django 3.2.18 on 2023-09-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20230904_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='max_salary_yen',
            new_name='max_salary',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='min_salary_yen',
            new_name='min_salary',
        ),
    ]
