# Generated by Django 3.2.18 on 2023-09-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_recruitingcompany_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='summary',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
