# Generated by Django 3.2.18 on 2023-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_recruitingcompany_name_index_trgrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
