# Generated by Django 3.2.18 on 2023-09-08 17:02

import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20230913_0048'),
    ]

    operations = [ 
        migrations.CreateModel(
            name='JobLoading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.ForeignKey(on_delete=models.deletion.CASCADE, to='api.organization')),
                ('user_id', models.ForeignKey(on_delete=models.deletion.CASCADE, to='api.user')),

                ('source_url', models.TextField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True, max_length=100)), 

                ('position', models.CharField(blank=True, null=True, max_length=100)),
                ('salary', models.TextField(blank=True, null=True, max_length=500)),
                ('employment_status', models.CharField(blank=True, null=True, max_length=50)),
                ('summary', models.TextField(blank=True, null=True, max_length=2000)),
                ('min_qualifications', models.TextField(blank=True, null=True, max_length=500)),
                ('pfd_qualifications', models.TextField(blank=True, null=True, max_length=500)),
                ('ideal_profile', models.TextField(blank=True, null=True, max_length=1000)),
                ('address', models.TextField(blank=True, null=True, max_length=500)),
                ('benefit', models.TextField(blank=True, null=True, max_length=1000)),
                ('other', models.TextField(blank=True, null=True, max_length=2000)),
                ('company_name', models.CharField(blank=True, null=True, max_length=150)),
                ('job_category_name', models.CharField(blank=True, null=True, max_length=40)),
                ('holiday', models.TextField(blank=True, null=True, max_length=500)),
                ('working_hours', models.TextField(blank=True, null=True, max_length=500)),
                ('smoking_prevention_measure', models.CharField(blank=True, null=True, max_length=50)),
                ('trial_period', models.CharField(blank=True, null=True, max_length=50)),
                ('layer', models.CharField(blank=True, null=True, max_length=20)),
                ('remote', models.CharField(blank=True, null=True, max_length=20)),
                ('min_salary', models.IntegerField(blank=True, null=True, max_length=20)),
                ('max_salary', models.IntegerField(blank=True, null=True, max_length=20)),

                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        )
    ]
