# Generated by Django 3.2.18 on 2023-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_create_job_loading_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobloading',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='jobloading',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='benefit',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='error',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='holiday',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='ideal_profile',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='job_category_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='layer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='min_qualifications',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='other',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='pfd_qualifications',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='remote',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='salary',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='smoking_prevention_measure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='source_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='summary',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='trial_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobloading',
            name='working_hours',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
