# Generated by Django 3.2.18 on 2023-10-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_job_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
