# Generated by Django 3.2.18 on 2023-10-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20231010_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='position',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='salary',
            field=models.TextField(blank=True),
        ),
    ]
