# Generated by Django 3.2.18 on 2023-10-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20231013_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='benefit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proposal',
            name='holiday',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='smoking_prevention_measure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='trial_period',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='working_hours',
            field=models.TextField(blank=True),
        ),
    ]
